blacklistedOres = []
spawnWithGuideBook = false
respawnWithGuideBook = false
disableFuelTooltips = true
disableItemTagTooltips = true
newVersionMessage = false
enableHatchPlacementOverlay = true
colorWaterLava = true
enableDebugCommands = false
enableAe2Integration = true
generateOres = true
